/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        brand: {
          50: '#f0fdf4',
          100: '#dcfce7',
          200: '#bbf7d0',
          300: '#86efac',
          400: '#4ade80',
          500: '#22c55e',
          600: '#16a34a',
          700: '#15803d',
          800: '#166534',
          900: '#145231',
          950: '#052e16',
        },
        priority: {
          p1: 'var(--color-priority-p1)',
          'p1-bg': 'var(--color-priority-p1-bg)',
          p2: 'var(--color-priority-p2)',
          'p2-bg': 'var(--color-priority-p2-bg)',
          p3: 'var(--color-priority-p3)',
          'p3-bg': 'var(--color-priority-p3-bg)',
          p4: 'var(--color-priority-p4)',
          'p4-bg': 'var(--color-priority-p4-bg)',
        },
        surface: {
          primary: 'var(--color-surface-primary)',
          secondary: 'var(--color-surface-secondary)',
          tertiary: 'var(--color-surface-tertiary)',
          elevated: 'var(--color-surface-elevated)',
          overlay: 'var(--color-surface-overlay)',
        },
        content: {
          primary: 'var(--color-text-primary)',
          secondary: 'var(--color-text-secondary)',
          tertiary: 'var(--color-text-tertiary)',
          inverse: 'var(--color-text-inverse)',
          disabled: 'var(--color-text-disabled)',
        },
        border: {
          DEFAULT: 'var(--color-border-default)',
          hover: 'var(--color-border-hover)',
          focus: 'var(--color-border-focus)',
          subtle: 'var(--color-border-subtle)',
        },
        interactive: {
          primary: 'var(--color-interactive-primary)',
          'primary-hover': 'var(--color-interactive-primary-hover)',
          'primary-active': 'var(--color-interactive-primary-active)',
          secondary: 'var(--color-interactive-secondary)',
          'secondary-hover': 'var(--color-interactive-secondary-hover)',
          'secondary-active': 'var(--color-interactive-secondary-active)',
        },
        semantic: {
          success: 'var(--color-success)',
          'success-light': 'var(--color-success-light)',
          'success-light-hover': 'var(--color-success-light-hover)',
          'success-hover': 'var(--color-success-hover)',
          warning: 'var(--color-warning)',
          'warning-light': 'var(--color-warning-light)',
          'warning-light-hover': 'var(--color-warning-light-hover)',
          'warning-hover': 'var(--color-warning-hover)',
          error: 'var(--color-error)',
          'error-light': 'var(--color-error-light)',
          'error-light-hover': 'var(--color-error-light-hover)',
          'error-hover': 'var(--color-error-hover)',
          info: 'var(--color-info)',
          'info-light': 'var(--color-info-light)',
          'info-light-hover': 'var(--color-info-light-hover)',
          'info-hover': 'var(--color-info-hover)',
        },
        hover: {
          subtle: 'var(--color-hover-subtle)',
        },
        active: {
          subtle: 'var(--color-active-subtle)',
        },
        skeleton: {
          base: 'var(--color-skeleton-base)',
          highlight: 'var(--color-skeleton-highlight)',
        },
        sidebar: {
          bg: 'var(--color-sidebar-bg)',
          hover: 'var(--color-sidebar-hover)',
          active: 'var(--color-sidebar-active)',
          text: 'var(--color-sidebar-text)',
          'text-muted': 'var(--color-sidebar-text-muted)',
        },
        input: {
          bg: 'var(--color-input-bg)',
          border: 'var(--color-input-border)',
          'border-hover': 'var(--color-input-border-hover)',
          'border-focus': 'var(--color-input-border-focus)',
          placeholder: 'var(--color-input-placeholder)',
          'disabled-bg': 'var(--color-input-disabled-bg)',
        },
        tooltip: {
          bg: 'var(--color-tooltip-bg)',
          text: 'var(--color-tooltip-text)',
        },
        accent: {
          purple: 'var(--color-accent-purple)',
          'purple-subtle': 'var(--color-accent-purple-subtle)',
          indigo: 'var(--color-accent-indigo)',
          'indigo-subtle': 'var(--color-accent-indigo-subtle)',
          teal: 'var(--color-accent-teal)',
          'teal-subtle': 'var(--color-accent-teal-subtle)',
        },
        icon: {
          success: 'var(--color-icon-success)',
          error: 'var(--color-icon-error)',
          warning: 'var(--color-icon-warning)',
          info: 'var(--color-icon-info)',
          purple: 'var(--color-icon-purple)',
          orange: 'var(--color-icon-orange)',
          teal: 'var(--color-icon-teal)',
          yellow: 'var(--color-icon-yellow)',
          indigo: 'var(--color-icon-indigo)',
          pink: 'var(--color-icon-pink)',
          cyan: 'var(--color-icon-cyan)',
        },
      },
      boxShadow: {
        none: 'var(--shadow-none)',
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        xl: 'var(--shadow-xl)',
        '2xl': 'var(--shadow-2xl)',
        inner: 'var(--shadow-inner)',
        glow: 'var(--shadow-glow)',
        elevated: 'var(--shadow-elevated)',
      },
      ringColor: {
        focus: 'var(--color-focus-ring)',
      },
      fontFamily: {
        sans: ['system-ui', 'sans-serif'],
      },
      fontSize: {
        sm: ['12px', '16px'],
        base: ['14px', '20px'],
        lg: ['16px', '24px'],
        xl: ['18px', '28px'],
        '2xl': ['20px', '28px'],
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '32px',
      },
      borderRadius: {
        sm: '4px',
        md: '6px',
        lg: '8px',
      },
      scale: {
        102: '1.02',
      },
      animation: {
        fadeIn: 'fadeIn 0.15s ease-in-out',
        slideUp: 'slideUp 0.3s ease-out',
        pulse: 'pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
      keyframes: {
        fadeIn: {
          from: { opacity: '0' },
          to: { opacity: '1' },
        },
        slideUp: {
          from: { transform: 'translateY(8px)', opacity: '0' },
          to: { transform: 'translateY(0)', opacity: '1' },
        },
      },
    },
  },
  plugins: [],
}
